import Head from 'next/head'

// blocks
import Banner from '../components/blocks/Banner'
import Categories from '../components/blocks/Categories'
import BuyOneGetOne from '../components/blocks/BuyOneGetOne'
import CategorySection from '../components/blocks/CategorySection'
import AdsCarousel from '../components/blocks/AdsCarousel'
import ViewByBrand from '../components/blocks/ViewByBrand'
import Footer from '../components/blocks/Footer'

export default function Home() {
	return (
		<>
			<Head>
				<title>MHS Frontend Task</title>
				<meta
					name='description'
					content='Generated by create next app'
				/>
				<link rel='icon' href='/icons/logo.svg' />
			</Head>

			<Banner />
			<Categories />
			<BuyOneGetOne />
			<CategorySection
				title='promotions'
				type='promotions'
				haveBottomBorder
			/>
			<CategorySection title='new arrivals' />

			<AdsCarousel />

			<ViewByBrand />

			<CategorySection
				title='phone'
				icon='/images/phone-category.jpg'
				haveBottomBorder
			/>
			<CategorySection
				title='laptop'
				icon='/images/laptop-category.jpg'
				haveBottomBorder
			/>
			<CategorySection
				title='tablet'
				icon='/images/tablet-category.jpg'
			/>

			<Footer />
		</>
	)
}
